# Employee Project Analysis using Python

## Business Analytics Capstone Project

**Tools Used:** Python, Pandas, NumPy

### Project Overview

This project demonstrates how Python can be used to clean, transform, merge, and analyze employee, project, and seniority datasets. The analysis includes handling missing values, applying business rules, performing data transformations, generating reports, and exporting processed datasets.

---

## Project Workflow & Business Tasks

This notebook is organized into the following business tasks:

1. Create Employee, Project and Seniority DataFrames
2. Handle Missing Project Costs
3. Split Employee Name into First and Last Name
4. Merge Employee, Seniority and Project Data
5. Calculate Employee Bonus
6. Update Employee Designation Levels
7. Add Employee Titles
8. Promote Employees Based on Age
9. Generate Project Cost Summary
10. Filter Employees by City

---

## Task 1 – Create Employee, Project and Seniority DataFrames

### Objective

Create three separate Pandas DataFrames for employees, projects, and seniority levels. Export each DataFrame as a CSV file to be used in subsequent business analysis tasks.

---

In [62]:
# ==================================================
# Task 1 : Create Employee, Project and Seniority DataFrames
# ==================================================

# Import the Pandas library
import pandas as pd

# Creating Employee DataFrame containing employee details.
Employee = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005"], "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
                         "Gender": ["M","F","M","F","F"], "City": ["Paris","London","Berlin","Newyork","Madrid"], "Age": [25, 27, 29, 31, 30]})

# Creating Seniority Level DataFrmae with ID and Designation Level.
Seniority = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005"], "Designation Level": [2,2,3,2,3]})

# Creating Project DataFrame with ID, Project, Cost and Status.
Project = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"], "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
                        "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000], "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]})

In [63]:
# Save all three DataFrames to .CSV file
Employee.to_csv("Employee.csv", index=False)
Seniority.to_csv("Seniority.csv", index=False)
Project.to_csv("Project.csv", index=False)

In [64]:
pd.read_csv("Employee.csv")

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [65]:
pd.read_csv("Seniority.csv")

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [66]:
pd.read_csv("Project.csv")

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

## Task 2 – Handle Missing Project Costs

### Objective

Replace missing values in the **Project Cost** column using the running average of previous project costs to ensure data completeness for business analysis.

---
The following code reads the project dataset and replaces missing project costs using a running average approach.

In [67]:
# ==================================================
# Task 2 : Handle Missing Project Costs
# ==================================================

Project = pd.read_csv("Project.csv")

# Initialize total and count for running average
total = 0
count = 0

# Loop through each row in the DataFrame
for i in range(len(Project)):
    # Check if Cost is NOT NaN
    if pd.notna(Project.loc[i, "Cost"]):
        # Add cost to total
        total += Project.loc[i, "Cost"]
        # Increase count
        count += 1
    else:
        # Replace NaN with running average
        Project.loc[i, "Cost"] = total/count

# Save updated DataFrmae
Project.to_csv("UpdatedProject.csv", index=False)

# Display updated DataFrame
Project

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

## Task 3 – Split Employee Names

### Objective

Separate employee names into **First Name** and **Last Name** columns to improve data organization and support reporting.

---
The following code separates employee names into individual first and last name columns for easier analysis.

In [68]:
# ==================================================
# Task 3 : Split Employee Names
# ==================================================

Employee = pd.read_csv("Employee.csv")

# Split the employee name into First Name and Last Name columns.
Employee[["First Name", "Last Name"]] = Employee["Name"].str.split(" ",expand=True)

# Remove the original Name column after splitting.
Employee = Employee.drop("Name", axis=1)

# Save updated DataFrmae
Employee.to_csv("UpdatedEmployee.csv", index=False)

# Display updated DataFrame
Employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

## Task 4 – Merge Employee, Seniority and Project Data

### Objective

Combine the employee, seniority, and project datasets into a single DataFrame using the **Employee ID**. Save the merged dataset for use in subsequent business analysis tasks.

---
The following code loads the updated datasets, merges them using the common **ID** column, and exports the consolidated dataset as a CSV file.

In [69]:
# ==================================================
# Task 4 : Merge Employee, Seniority and Project Data
# ==================================================

Employee = pd.read_csv("UpdatedEmployee.csv")
Seniority = pd.read_csv("Seniority.csv")
Project = pd.read_csv("UpdatedProject.csv")

# Merge the Employee and Seniority DataFrames using Employee ID.
Final = pd.merge(Employee, Seniority, on="ID")

# Merge the resulting DataFrame with the Project DataFrame.
Final = pd.merge(Final, Project, on="ID")

# Export the merged DataFrame as a CSV file.
Final.to_csv("Final.csv", index=False)

# Display the final merged DataFrame.
display(Final)

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

## Task 5 – Calculate Employee Bonus

### Objective

Calculate a **5% bonus** for employees whose project status is **Finished**. Employees working on ongoing or failed projects are assigned a bonus of zero.

---
The following code uses NumPy's conditional function to calculate the bonus and updates the final dataset.

In [70]:
# ==================================================
# Task 5 : Calculate Employee Bonus
# ==================================================

import numpy as np

# Calculate a 5% bonus for employees with completed projects.
Final["Bonus"] = np.where(Final["Status"] == "Finished",
                          Final["Cost"]*0.05, 0)

# Save the updated DataFrame as a CSV file.
Final.to_csv("Final.csv", index=False)

# Display the updated DataFrame.
display(Final)

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

## Task 6 – Update Employee Designation Levels

### Objective

Increase the **Designation Level** by one for employees whose project status is **Failed**. Remove any employees whose designation level exceeds the maximum allowed level after the update.

---
The following code updates designation levels based on project status and filters the dataset according to the business rule.

In [71]:
# ==================================================
# Task 6 : Update Employee Designation Levels
# ==================================================

# Increase the designation level by one for employees with failed projects.
Final.loc[Final["Status"] == "Failed", "Designation Level"] +=1

# Remove employees whose designation level exceeds 4.
Final = Final[Final["Designation Level"]<=4]

# Save the updated DataFrame as a CSV file.
Final.to_csv("Final.csv", index=False)

# Display the updated DataFrame.
display(Final)

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

## Task 7 – Add Employee Titles

### Objective

Add appropriate titles (**Mr.** or **Mrs.**) to employee first names based on gender. After adding the titles, remove the **Gender** column since it is no longer required for reporting.

---

In [72]:
# ==================================================
# Task 7 : Add Employee Titles
# ==================================================

# Add titles to employee first names based on gender.
Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final["First Name"]

# Remove the Gender column after adding titles.
Final = Final.drop("Gender", axis=1)

# Save the updated DataFrame as a CSV file.
Final.to_csv("Final.csv", index=False)

# Display the updated DataFrame.
display(Final)

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

## Task 8 – Promote Employees Based on Age

### Objective

Promote employees who are **older than 29 years** by improving their designation level according to the business rule.

The updated designation levels are then saved to the final dataset.

---

In [73]:
# ==================================================
# Task 8 : Promote Employees Based on Age
# ==================================================

# Iterate through each employee record.
for i in range(len(Final)):
    # Promote employees older than 29 years.
    if Final.loc[i, "Age"]>29:
        # Reduce the designation level by one (promotion).
        Final.loc[i, "Designation Level"] -= 1

# Save the updated DataFrame as a CSV file.
Final.to_csv("Final.csv", index=False)

# Display the updated DataFrame.
display(Final)

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

## Task 9 – Generate Project Cost Summary

### Objective

Calculate the total project cost incurred by each employee by grouping records based on employee ID and name.

This summary provides a consolidated view of project spending per employee.

---

In [74]:
# ==================================================
# Task 9 : Generate Project Cost Summary
# ==================================================

# Calculate the total project cost for each employee.
TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename the aggregated Cost column.
TotalProjCost.rename(columns={"Cost":"Total Cost"}, inplace=True)

# Display the summarized project cost.
display(TotalProjCost)

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

## Task 10 – Filter Employees by City

### Objective

Retrieve all employee records where the **City** contains the letter **'o'** (case-insensitive).

This demonstrates text filtering using Pandas string functions.

---

In [75]:
# ==================================================
# Task 10 : Filter Employees by City
# ==================================================

# Filter employees whose city contains the letter 'o'.
filtered_city = Final[Final["City"].str.contains("o", case=False)]

# Display the filtered employee records.
display(filtered_city)

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2000000.0,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,680000.0,Failed,0.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5500000.0,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1000000.0,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3000000.0,Finished,150000.0

# Conclusion

This project demonstrates how Python and Pandas can be used to solve common business analytics problems, including:

- Data cleaning
- Missing value handling
- Data transformation
- Data merging
- Conditional business rules
- Employee analytics
- Cost analysis
- Reporting
- CSV export

This notebook showcases practical Python and Pandas techniques commonly used in real-world business analytics, reporting, and data preparation workflows.