In [1]:
a = 'Hello Hi'
print (a)

Hello Hi

In [2]:
#TASK 1 

# Import pandas
import pandas as pd

# Creating Employee DataFrame with ID, Name, Gender, City and Age.
Employee = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005"], "Name": ["John Alter","Alice Luxumberg","Tom Sabestine","Nina Adgra","Amy Johny"],
                         "Gender": ["M","F","M","F","F"], "City": ["Paris","London","Berlin","Newyork","Madrid"], "Age": [25, 27, 29, 31, 30]})

# Creating Seniority Level DataFrmae with ID and Designation Level.
Seniority = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005"], "Designation Level": [2,2,3,2,3]})

# Creating Project DataFrame with ID, Project, Cost and Status.
Project = pd.DataFrame({"ID": ["A001","A002","A003","A004","A005","A002","A005","A003","A001","A003","A001","A004","A004","A005"], "Project": ["Project 1","Project 2","Project 3","Project 4","Project 5","Project 6","Project 7","Project 8","Project 9","Project 10","Project 11","Project 12","Project 13","Project 14"],
                        "Cost": [1002000,2000000,4500000,5500000,None,680000,400000,350000,None,300000,2000000,1000000,3000000,200000], "Status": ["Finished","Ongoing","Finished","Ongoing","Finished","Failed","Finished","Failed","Ongoing","Finished","Failed","Ongoing","Finished","Finished"]})

In [3]:
# Saving all three DataFrames to .CSV file
Employee.to_csv("Employee.csv", index=False)
Seniority.to_csv("Seniority.csv", index=False)
Project.to_csv("Project.csv", index=False)

In [4]:
pd.read_csv("Employee.csv")

     ID             Name Gender     City  Age
0  A001       John Alter      M    Paris   25
1  A002  Alice Luxumberg      F   London   27
2  A003    Tom Sabestine      M   Berlin   29
3  A004       Nina Adgra      F  Newyork   31
4  A005        Amy Johny      F   Madrid   30

In [5]:
pd.read_csv("Seniority.csv")

     ID  Designation Level
0  A001                  2
1  A002                  2
2  A003                  3
3  A004                  2
4  A005                  3

In [6]:
pd.read_csv("Project.csv")

      ID     Project       Cost    Status
0   A001   Project 1  1002000.0  Finished
1   A002   Project 2  2000000.0   Ongoing
2   A003   Project 3  4500000.0  Finished
3   A004   Project 4  5500000.0   Ongoing
4   A005   Project 5        NaN  Finished
5   A002   Project 6   680000.0    Failed
6   A005   Project 7   400000.0  Finished
7   A003   Project 8   350000.0    Failed
8   A001   Project 9        NaN   Ongoing
9   A003  Project 10   300000.0  Finished
10  A001  Project 11  2000000.0    Failed
11  A004  Project 12  1000000.0   Ongoing
12  A004  Project 13  3000000.0  Finished
13  A005  Project 14   200000.0  Finished

In [7]:
# TASK 1 Completed = Three dataframe created and saved them as .csv files.

In [8]:
#TASK 2

Project = pd.read_csv("Project.csv")

# Initialize total and count for running average
total = 0
count = 0

# Loop through each row in the DataFrame
for i in range(len(Project)):
    # Check if Cost is NOT NaN
    if pd.notna(Project.loc[i, "Cost"]):
        # Add cost to total
        total += Project.loc[i, "Cost"]
        # Increase count
        count += 1
    else:
        # Replace NaN with running average
        Project.loc[i, "Cost"] = total/count

# Save updated DataFrmae
Project.to_csv("UpdatedProject.csv", index=False)

# Display updated DataFrame
Project

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [9]:
# TASK 2 Completed = Replaced the missing values in Cost column by running average

In [10]:
#TASK 3

Employee = pd.read_csv("Employee.csv")

# Splitting Name into First Name and Last Name
Employee[["First Name", "Last Name"]] = Employee["Name"].str.split(" ",expand=True)

# Removing original Name column
Employee = Employee.drop("Name", axis=1)

# Save updated DataFrmae
Employee.to_csv("UpdatedEmployee.csv", index=False)

# Display updated DataFrame
Employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sabestine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [11]:
# TASK 3 Completed = Two new columns "First Name" & "Last Name” created and removed the older "Name" column.

In [12]:
#TASK 4

Employee = pd.read_csv("UpdatedEmployee.csv")
Seniority = pd.read_csv("Seniority.csv")
Project = pd.read_csv("UpdatedProject.csv")

# Merge Employee and Seniority DataFrames
Final = pd.merge(Employee, Seniority, on="ID")

# Merge the above result with Project DataFrame
Final = pd.merge(Final, Project, on="ID")

# Saving merged DataFrame(Final) to .CSV for reference
Final.to_csv("Final.csv", index=False)

# Display Final DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished

In [13]:
# TASK 4 Completed = Created one single dataframe by joining all three DataFrames.

In [14]:
#TASK 5

import numpy as np

# Creating Bonus column based on condition
Final["Bonus"] = np.where(Final["Status"] == "Finished",
                          Final["Cost"]*0.05, 0)

# Saving this change in Final DataFrame
Final.to_csv("Final.csv", index=False)

# Display updated DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,2,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,2,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,3,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [15]:
# TASK 5 Completed = A new bonus(5% bonus for finished projects) column created in the Final dataframe.

In [16]:
#TASK 6

# Increase designation level by 1 where project status is "Failed"
Final.loc[Final["Status"] == "Failed", "Designation Level"] +=1

# Remove employees whose Designation Level is greater than 4
Final = Final[Final["Designation Level"]<=4]

# Save this update in Final DataFrame
Final.to_csv("Final.csv", index=False)

# Display updated DataFrame
Final

,ID,Gender,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,M,Paris,25,John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,M,Paris,25,John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,M,Paris,25,John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,F,London,27,Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,F,London,27,Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,M,Berlin,29,Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,M,Berlin,29,Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,M,Berlin,29,Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,F,Newyork,31,Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,F,Newyork,31,Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,F,Newyork,31,Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,F,Madrid,30,Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,F,Madrid,30,Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,F,Madrid,30,Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [17]:
# TASK 6 Completed = Designation Level changed for employees with failed project status.
# Note: No employee has a designation level above 4.

In [18]:
#TASK 7

# Adding prefix Mr. to male employees and Mrs. to female employees.
Final.loc[Final["Gender"] == "M", "First Name"] = "Mr. " + Final["First Name"]
Final.loc[Final["Gender"] == "F", "First Name"] = "Mrs. " + Final["First Name"]

# Drop Gender column
Final = Final.drop("Gender", axis=1)

# Save this updated data in Final DataFrame
Final.to_csv("Final.csv", index=False)

# Display updated DataFrame
Final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,2,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,3,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,3,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,3,Project 14,2.000000e+05,Finished,10000.0

In [19]:
# TASK 7 Completed = Gender column removed. Prefix “Mr.” and “Mrs.” added to the first name column.

In [20]:
#TASK 8

# Loop through each row in the DataFrame
for i in range(len(Final)):
    # Checking if age is greater than 29
    if Final.loc[i, "Age"]>29:
        # Promote designation level, by reducing it by 1
        Final.loc[i, "Designation Level"] -= 1

# Save this changes
Final.to_csv("Final.csv", index=False)

# Display updated DataFrame
Final

,ID,City,Age,First Name,Last Name,Designation Level,Project,Cost,Status,Bonus
0,A001,Paris,25,Mr. John,Alter,2,Project 1,1.002000e+06,Finished,50100.0
1,A001,Paris,25,Mr. John,Alter,2,Project 9,2.061714e+06,Ongoing,0.0
2,A001,Paris,25,Mr. John,Alter,3,Project 11,2.000000e+06,Failed,0.0
3,A002,London,27,Mrs. Alice,Luxumberg,2,Project 2,2.000000e+06,Ongoing,0.0
4,A002,London,27,Mrs. Alice,Luxumberg,3,Project 6,6.800000e+05,Failed,0.0
5,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 3,4.500000e+06,Finished,225000.0
6,A003,Berlin,29,Mr. Tom,Sabestine,4,Project 8,3.500000e+05,Failed,0.0
7,A003,Berlin,29,Mr. Tom,Sabestine,3,Project 10,3.000000e+05,Finished,15000.0
8,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 4,5.500000e+06,Ongoing,0.0
9,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 12,1.000000e+06,Ongoing,0.0
10,A004,Newyork,31,Mrs. Nina,Adgra,1,Project 13,3.000000e+06,Finished,150000.0
11,A005,Madrid,30,Mrs. Amy,Johny,2,Project 5,3.250500e+06,Finished,162525.0
12,A005,Madrid,30,Mrs. Amy,Johny,2,Project 7,4.000000e+05,Finished,20000.0
13,A005,Madrid,30,Mrs. Amy,Johny,2,Project 14,2.000000e+05,Finished,10000.0

In [21]:
# TASK 8 Completed = Promoted the designation level by 1 for employees whose age is more than 29 years.

In [22]:
#TASK 9

# Group data by ID and First Name, then calculate total project cost.
TotalProjCost = Final.groupby(["ID", "First Name"])["Cost"].sum().reset_index()

# Rename Cost column to Total Cost
TotalProjCost.rename(columns={"Cost":"Total Cost"}, inplace=True)

# Display new DataFrame
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [23]:
# TASK 9 Completed = Created a new DataFrame “TotalProjCost” containing three columns with the total project cost for each employee.

In [24]:
#TASK 10

# Filter employees whose city contains letter 'o'
city_o = Final[Final["City"].str.contains("o", case=False)]

print(city_o)

      ID     City  Age  First Name  Last Name  Designation Level     Project  \
3   A002   London   27  Mrs. Alice  Luxumberg                  2   Project 2
4   A002   London   27  Mrs. Alice  Luxumberg                  3   Project 6
8   A004  Newyork   31   Mrs. Nina      Adgra                  1   Project 4
9   A004  Newyork   31   Mrs. Nina      Adgra                  1  Project 12
10  A004  Newyork   31   Mrs. Nina      Adgra                  1  Project 13

         Cost    Status     Bonus
3   2000000.0   Ongoing       0.0
4    680000.0    Failed       0.0
8   5500000.0   Ongoing       0.0
9   1000000.0   Ongoing       0.0
10  3000000.0  Finished  150000.0

In [25]:
# TASK 10 Completed.